// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1556210809);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1556210929);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1556210329);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1556210569);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1556210449);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1556210689);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1556211169);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1556211049);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1556210299);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4e89a8df-a59e-4a42-b5f3-4e0952842f78}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1556150400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1556210301");
user_pref("browser.slowStartup.averageTime", 2476);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190410105841");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1556210990);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"52992d23-6a4c-4bad-86d4-5299cc87d593\",\"screenshots@mozilla.org\":\"37d77ade-76e5-4952-b108-c33e07cdc3ce\",\"webcompat-reporter@mozilla.org\":\"bb0ec665-e5e8-4ae8-a0f4-7f07b209ac7f\",\"webcompat@mozilla.org\":\"912c9bc8-8384-49b6-af1a-451e9947c2bd\"}");
user_pref("idle.lastDailyNotification", 1556210495);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190410105841");
user_pref("media.gmp-manager.lastCheck", 1556210356);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 3128);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1556210495);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "f206c396-4c94-4815-ac4c-6df60cda6aaf");
user_pref("security.sandbox.plugin.tempDirSuffix", "f5a9e40a-6f58-4cab-b6f2-54bafe5dc4b7");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1556210495);
user_pref("toolkit.startup.last_success", 1556210298);
user_pref("toolkit.telemetry.cachedClientID", "48d4f80e-ae5e-4f1f-9eba-3e7d8699eca0");
user_pref("toolkit.telemetry.previousBuildID", "20190410105841");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
